# EOCT CONFIGURATION FILE - SECONDARY MATHEMATICS
#############################################################
SEC_MATH_I_2015.config <- list(
	SEC_MATH_I.2015 = list(
		sgp.content.areas=c('SEC_MATH_I','SEC_MATH_I'), #Repeater
		sgp.panel.years=as.character(2014:2015),
		sgp.grade.sequences=list(c('EOCT','EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=0),
	SEC_MATH_I.2015 = list(
		sgp.content.areas=c(rep('MATHEMATICS', 5), 'SEC_MATH_I'),
		sgp.panel.years=as.character(2010:2015),
		sgp.grade.sequences=list(c(4:8,'EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=1),
	SEC_MATH_I.2015 = list(
		sgp.content.areas=c(rep('MATHEMATICS', 4), 'SEC_MATH_I'),
		sgp.panel.years=as.character(2011:2015),
		sgp.grade.sequences=list(c(5:8,'EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=2),	
	SEC_MATH_I.2015 = list(
		sgp.content.areas=c(rep('MATHEMATICS', 3), 'SEC_MATH_I'),
		sgp.panel.years=as.character(2012:2015),
		sgp.grade.sequences=list(c(6:8,'EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=3),
	SEC_MATH_I.2015 = list(
		sgp.content.areas=c(rep('MATHEMATICS', 2), 'SEC_MATH_I'),
		sgp.panel.years=as.character(2013:2015),
		sgp.grade.sequences=list(c(7:8,'EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=4),
	SEC_MATH_I.2015 = list(
		sgp.content.areas=c('MATHEMATICS', 'SEC_MATH_I'),
		sgp.panel.years=as.character(2014:2015),
		sgp.grade.sequences=list(c(8,'EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=5),
# ACCELERATED (MATH 8 TAKEN IN SAME YEAR AS SEC_MATH_I)
	SEC_MATH_I.2015 = list(
		sgp.content.areas=c(rep('MATHEMATICS', 5), 'SEC_MATH_I'),
		sgp.panel.years=as.character(2010:2015),
		sgp.grade.sequences=list(c(3:7,'EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=1),
	SEC_MATH_I.2015 = list(
		sgp.content.areas=c(rep('MATHEMATICS', 4), 'SEC_MATH_I'),
		sgp.panel.years=as.character(2011:2015),
		sgp.grade.sequences=list(c(4:7,'EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=2),	
	SEC_MATH_I.2015 = list(
		sgp.content.areas=c(rep('MATHEMATICS', 3), 'SEC_MATH_I'),
		sgp.panel.years=as.character(2012:2015),
		sgp.grade.sequences=list(c(5:7,'EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=3),
	SEC_MATH_I.2015 = list(
		sgp.content.areas=c(rep('MATHEMATICS', 2), 'SEC_MATH_I'),
		sgp.panel.years=as.character(2013:2015),
		sgp.grade.sequences=list(c(6:7,'EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=4),
	SEC_MATH_I.2015 = list(
		sgp.content.areas=c('MATHEMATICS', 'SEC_MATH_I'),
		sgp.panel.years=as.character(2014:2015),
		sgp.grade.sequences=list(c(7,'EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=5)
)
#############################################################
SEC_MATH_II_2015.config <- list(
	SEC_MATH_II.2015 = list(
		sgp.content.areas=c('SEC_MATH_II','SEC_MATH_II'), #Repeater
		sgp.panel.years=as.character(2014:2015),
		sgp.grade.sequences=list(c('EOCT','EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=0),
	SEC_MATH_II_2015 = list(
		sgp.content.areas=c(rep('MATHEMATICS', 3), 'PRE_ALGEBRA', 'SEC_MATH_I', 'SEC_MATH_II'),
		sgp.panel.years=c(2010:2015),
		sgp.grade.sequences=list(c(5:7, 'EOCT', 'EOCT', 'EOCT')),  
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=1),
	SEC_MATH_II_2015 = list(
		sgp.content.areas=c(rep('MATHEMATICS', 2), 'PRE_ALGEBRA', 'SEC_MATH_I', 'SEC_MATH_II'),
		sgp.panel.years=c(2011:2015),
		sgp.grade.sequences=list(c(6:7, 'EOCT', 'EOCT', 'EOCT')),  
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=2),
	SEC_MATH_II_2015 = list(
		sgp.content.areas=c('MATHEMATICS', 'PRE_ALGEBRA', 'SEC_MATH_I', 'SEC_MATH_II'),
		sgp.panel.years=c(2012:2015),
		sgp.grade.sequences=list(c(7, 'EOCT', 'EOCT', 'EOCT')),  
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=3),
	SEC_MATH_II_2015 = list(
		sgp.content.areas=c('PRE_ALGEBRA', 'SEC_MATH_I', 'SEC_MATH_II'),
		sgp.panel.years=c(2013:2015),
		sgp.grade.sequences=list(c('EOCT', 'EOCT', 'EOCT')),  
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=4),
	SEC_MATH_II_2015 = list(
		sgp.content.areas=c('SEC_MATH_I', 'SEC_MATH_II'),
		sgp.panel.years=c(2014:2015),
		sgp.grade.sequences=list(c('EOCT', 'EOCT')),  
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=5)
)
#############################################################
SEC_MATH_III_2015.config <- list(
  SEC_MATH_III.2015 = list(
		sgp.content.areas=c('SEC_MATH_III','SEC_MATH_III'), #Repeater
		sgp.panel.years=as.character(2014:2015),
		sgp.grade.sequences=list(c('EOCT','EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=0),
# VIA ALGEBRA 1
	SEC_MATH_III_2015 = list(
		sgp.content.areas=c('MATHEMATICS','PRE_ALGEBRA','ALGEBRA_I','SEC_MATH_II','SEC_MATH_III'),
		sgp.panel.years=c(2010:2012,2014:2015),
		sgp.grade.sequences=list(c(6, 'EOCT','EOCT','EOCT','EOCT')),  
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=1),
	SEC_MATH_III_2015 = list(
		sgp.content.areas=c('PRE_ALGEBRA','ALGEBRA_I','SEC_MATH_II','SEC_MATH_III'),
		sgp.panel.years=c(2011:2012,2014:2015),
		sgp.grade.sequences=list(c('EOCT','EOCT','EOCT','EOCT')),  
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=2),
	SEC_MATH_III_2015 = list(
		sgp.content.areas=c('ALGEBRA_I','SEC_MATH_II','SEC_MATH_III'),
		sgp.panel.years=c("2012",2014:2015),
		sgp.grade.sequences=list(c('EOCT','EOCT','EOCT','EOCT')),  
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=3),
# SKIP ALGEBRA 1
  SEC_MATH_III_2015 = list(
		sgp.content.areas=c(rep('MATHEMATICS', 2),'PRE_ALGEBRA','SEC_MATH_II','SEC_MATH_III'),
		sgp.panel.years=c(2010:2012,2014:2015),
		sgp.grade.sequences=list(c(6:7,'EOCT','EOCT','EOCT')),  
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=1),
	SEC_MATH_III_2015 = list(
		sgp.content.areas=c('MATHEMATICS','PRE_ALGEBRA','SEC_MATH_II','SEC_MATH_III'),
		sgp.panel.years=c(2011:2012,2014:2015),
		sgp.grade.sequences=list(c(7,'EOCT','EOCT','EOCT')),  
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=2),
	SEC_MATH_III_2015 = list(
		sgp.content.areas=c('PRE_ALGEBRA_I','SEC_MATH_II','SEC_MATH_III'),
		sgp.panel.years=c("2012",2014:2015),
		sgp.grade.sequences=list(c('EOCT','EOCT','EOCT')),  
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=3),
  SEC_MATH_III.2015 = list(
		sgp.content.areas=c('SEC_MATH_II','SEC_MATH_III'),  
		sgp.panel.years=as.character(2014:2015),
		sgp.grade.sequences=list(c('EOCT','EOCT')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=4)
)